language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t pastiubogdan/docker-react -f Dockerfile.dev .
  
script:
  - docker run pastiubogdan/docker-react npm run test -- --coverage